# Generated by Django 5.1.1 on 2024-09-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teachers_teachers_situation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images/achievement/')),
            ],
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subjects',
            field=models.CharField(choices=[('Ingliz tili', 'Ingliz tili'), ('Rus tili', 'Rus tili'), ('Algebra', 'Algebra'), ('Geometriya', 'Geometriya'), ('Astronomiya', 'Astronomiya'), ('Fizika', 'Fizika'), ('Biologiya', 'Biologiya'), ('kimyo', 'kimyo'), ('geografiya', 'geografiya'), ('ona tili', 'ona tili'), ('Adabiyot', 'Adabiyot'), ('CHQBT', 'CHQBT'), ('Informatika', 'Informatika'), ('Davlat huquq asoslari', 'Davlat huquq asoslari'), ('Jahon tarixi', 'Jahon tarixi'), ("O'zbekiston tarixi", "O'zbekiston tarixi"), ('Chizmachilik', 'Chizmachilik'), ('Musiqa', 'Musiqa'), ('Jismoniy tarbiya', 'Jismoniy tarbiya')], max_length=200),
        ),
    ]
