# Generated by Django 5.1.1 on 2024-10-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_acceptance_alter_comments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
