# Generated by Django 5.1.1 on 2024-10-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_acceptance_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptance',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
