# Generated by Django 5.1.1 on 2024-10-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_acceptance_phone_number_alter_acceptance_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptance',
            name='slug',
        ),
    ]
