# Generated by Django 5.1.1 on 2024-10-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_acceptance_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptance',
            options={'verbose_name': 'Acceptance', 'verbose_name_plural': 'Acceptances'},
        ),
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'news_Image', 'verbose_name_plural': 'news_Images'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'ordering': ['-id'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='teachers_situation',
            options={'verbose_name': 'Teacher_situation', 'verbose_name_plural': 'Teachers_situations'},
        ),
        migrations.AddField(
            model_name='achievements',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
