# Generated by Django 5.1.1 on 2024-10-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_acceptance_options_alter_achievements_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='student_image',
            field=models.ImageField(default=1, upload_to='images/achievement/students/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievements',
            name='image',
            field=models.ImageField(upload_to='images/achievement/certificate/'),
        ),
    ]
