# Generated by Django 5.1.1 on 2024-10-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_achievements_student_image_alter_achievements_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='lessons',
            field=models.ImageField(blank=True, null=True, upload_to='images/teacher_lesson'),
        ),
    ]
