# Generated by Django 5.1.1 on 2024-10-15 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_boss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='student_image',
        ),
    ]
